version: '3.8'
services:
  spring-service:
    env_file:
      - .env
    container_name: spring-container
    image: hyeesw/spring-app
    ports:
      - "8080:8080"
    depends_on:
      mysql-service:
        condition: service_healthy
      redis-service:
        condition: service_healthy
    networks:
      - backend-network

  mysql-service:
    container_name: mysql-container
    image: mysql:latest
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - backend-network

  redis-service:
    container_name: redis-container
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - backend-network

networks:
  backend-network:
